Update dependencies to fix build
`yarn` wasn't working for me due to:

    SyntaxError: Named export 'onExit' not found. The requested module 'signal-exit' is a CommonJS module, which may not support all module.exports as named exports.

I asked Claude for help and it did the dependency updates to fix the problem. Now I can run `yarn` and `heroku plugins:link` successfully.

Refs https://salesforce-internal.slack.com/archives/C0A287B3KD4/p1773944089561669?thread_ts=1773940908.535739&cid=C0A287B3KD4